Pandas

In [1]:
import pandas as pd

## Sections

In [2]:
units = pd.read_csv("UC_sections.csv",delimiter=",",skiprows=lambda i: i >= 3)
units

,Section,m/L,h,b,tw,tf,r,d,cw / tw,cf/tf,...,rgzz,Syy,Szz,Wyy,Wzz,U,X,Iw,IT,A
0,Section designation,Mass per metre,Depth of section,Width of section,Thickness Web,Thickness Flange,Root radius,Depth between fillets,Ratios for local buckling - Web,Ratios for local buckling - Flange,...,Radius of gyration: Axis z-z,Elastic modulus: Axis y-y,Elastic modulus: Axis z-z,Plastic modulus: Axis y-y,Plastic modulus: Axis z-z,Buckling parameter,Torsional index,Warping constant,Torsional constant,Area of section
1,NaN,kg/m,mm,mm,mm,mm,mm,mm,NaN,NaN,...,cm,cm3,cm3,cm3,cm3,NaN,NaN,Iw [dm6],IT [cm4],A [cm2]

In [3]:
UC_sections = pd.read_csv("UC_sections.csv",delimiter=",",skiprows=[1,2])
UB_sections = pd.read_csv("UB_sections.csv",delimiter=",",skiprows=[1,2])

In [4]:
UC_sections.loc[UC_sections["Section"] == "356x406x744", "Iyy"].iloc[0]

np.int64(342000)

## Section resistance

$F_{Rd} = \sigma * A$

$M_{Rd,y} = W_{yy} * \sigma$

In [5]:
sigma = 355E6 # Pa

In [6]:
UB_sections

,Section,m/L,h,b,tw,tf,r,d,cw / tw,cf/tf,...,rgzz,Syy,Szz,Wyy,Wzz,U,X,Iw,IT,A
0,1016x305x584,584.0,1056.0,314.0,36.0,64.0,30.0,868.1,24.1,1.70,...,6.70,23600.0,2130.0,28000.0,3480.0,0.869,18.0,81.2000,7150.00,744.0
1,1016x305x494,494.0,1036.0,309.0,31.0,54.0,30.0,868.1,28.0,2.02,...,6.53,19800.0,1740.0,23400.0,2820.0,0.867,20.9,64.0000,4400.00,629.0
2,1016x305x438,438.0,1026.0,305.0,26.9,49.0,30.0,868.1,32.3,2.23,...,6.49,17700.0,1540.0,20800.0,2470.0,0.869,23.1,56.0000,3190.00,556.0
3,1016x305x415,415.0,1020.0,304.0,26.0,46.0,30.0,868.1,33.4,2.37,...,6.41,16700.0,1430.0,19600.0,2300.0,0.868,24.3,51.1000,2700.00,529.0
4,1016x305x393,392.7,1015.9,303.0,24.4,43.9,30.0,868.1,35.6,2.49,...,6.40,15900.0,1350.0,18500.0,2170.0,0.867,25.5,48.4000,2330.00,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,203x133x25,25.1,203.2,133.2,5.7,7.8,7.6,172.4,30.2,7.20,...,3.10,230.0,46.2,258.0,70.9,0.877,25.6,0.0294,5.96,32.0
103,203x102x23,23.1,203.2,101.8,5.4,9.3,7.6,169.4,31.4,4.37,...,2.36,207.0,32.2,234.0,49.7,0.888,22.4,0.0154,7.02,29.4
104,178x102x19,19.0,177.8,101.2,4.8,7.9,7.6,146.8,30.6,5.14,...,2.37,153.0,27.0,171.0,41.6,0.886,22.6,0.0099,4.41,24.3
105,152x89x16,16.0,152.4,88.7,4.5,7.7,7.6,121.8,27.1,4.48,...,2.10,109.0,20.2,123.0,31.2,0.889,19.5,0.0047,3.56,20.3
106,127x76x13,13.0,127.0,76.0,4.0,7.6,7.6,96.6,24.2,3.74,...,1.84,74.6,14.7,84.2,22.6,0.894,16.3,0.0020,2.85,16.5

In [7]:
UB_resistance = UB_sections[["Section"]].copy()
UB_resistance["F_Rd"] = UB_sections["A"] * 1e-4 * sigma
UB_resistance["M_yy_Rd"] = UB_sections["Wyy"] * 1e-6 * sigma
UB_resistance["M_zz_Rd"] = UB_sections["Wzz"] * 1e-6 * sigma
UB_resistance["Section"] = "UB" + UB_sections["Section"].astype(str)
UB_resistance

            Section        F_Rd    M_yy_Rd    M_zz_Rd
0    UB1016x305x584  26412000.0  9940000.0  1235400.0
1    UB1016x305x494  22329500.0  8307000.0  1001100.0
2    UB1016x305x438  19738000.0  7384000.0   876850.0
3    UB1016x305x415  18779500.0  6958000.0   816500.0
4    UB1016x305x393  17750000.0  6567500.0   770350.0
..              ...         ...        ...        ...
102    UB203x133x25   1136000.0    91590.0    25169.5
103    UB203x102x23   1043700.0    83070.0    17643.5
104    UB178x102x19    862650.0    60705.0    14768.0
105     UB152x89x16    720650.0    43665.0    11076.0
106     UB127x76x13    585750.0    29891.0     8023.0

[107 rows x 4 columns]

In [8]:
UC_resistance = UC_sections[["Section"]].copy()
UC_resistance["F_Rd"] = UC_sections["A"] * 1e-4 * sigma
UC_resistance["M_yy_Rd"] = UC_sections["Wyy"] * 1e-6 * sigma
UC_resistance["M_zz_Rd"] = UC_sections["Wzz"] * 1e-6 * sigma
UC_resistance["Section"] = "UC" + UC_resistance["Section"].astype(str)

In [9]:
resistances = pd.concat([UB_resistance,UC_resistance]).reset_index(drop=True)
resistances

            Section        F_Rd    M_yy_Rd    M_zz_Rd
0    UB1016x305x584  26412000.0  9940000.0  1235400.0
1    UB1016x305x494  22329500.0  8307000.0  1001100.0
2    UB1016x305x438  19738000.0  7384000.0   876850.0
3    UB1016x305x415  18779500.0  6958000.0   816500.0
4    UB1016x305x393  17750000.0  6567500.0   770350.0
..              ...         ...        ...        ...
148    UC152x152x51   2314600.0   155490.0    70645.0
149    UC153x152x44   1991550.0   132060.0    59995.0
150    UC154x152x37   1672050.0   109695.0    49700.0
151    UC155x152x30   1359650.0    88040.0    39760.0
152    UC156x152x23   1036600.0    64610.0    28435.5

[153 rows x 4 columns]

## Beam elements

In [10]:
lines_position = pd.read_csv("lines_position.csv",delimiter=",",skipinitialspace=True)
lines_position

     Line  Node 1  Node 2  Start X  Start Y  Start Z  End X  End Y  End Z
0       1       1       5      0.0      0.0      0.0    0.0    0.0    5.0
1       2       2       6      6.0      0.0      0.0    6.0    0.0    5.0
2       3       3       7     12.0      0.0      0.0   12.0    0.0    5.0
3       4       4       8     18.0      0.0      0.0   18.0    0.0    5.0
4       5       9       5      0.0      8.0      5.0    0.0    0.0    5.0
..    ...     ...     ...      ...      ...      ...    ...    ...    ...
463   520     309     317     12.0     24.0     25.0   12.0   32.0   25.0
464   521     317     334     12.0     32.0     25.0   15.0   32.0   25.0
465   522     331     334     15.0     24.0     25.0   15.0   32.0   25.0
466   523     334     319     15.0     32.0     25.0   18.0   32.0   25.0
467   524     311     319     18.0     24.0     25.0   18.0   32.0   25.0

[468 rows x 9 columns]

In [11]:
elements = pd.read_csv("elements_lines.csv",delimiter=",",skipinitialspace=True)
elements

      Element  Line
0           1    53
1           2    53
2           3    53
3           4    53
4           5    41
...       ...   ...
4171     4172   465
4172     4173   466
4173     4174   466
4174     4175   466
4175     4176   466

[4176 rows x 2 columns]

In [12]:
line_section = pd.read_csv("lines_sections.csv",delimiter=",",skipinitialspace=True)
line_section

     line       section
0       1  UC203x203x60
1       2  UC203x203x60
2       3  UC203x203x60
3       4  UC203x203x60
4       5  UB457x191x67
..    ...           ...
463   520  UB457x191x67
464   521  UB533x210x82
465   522  UB457x191x67
466   523  UB533x210x82
467   524  UB457x191x67

[468 rows x 2 columns]

## Element results

In [13]:
DL = pd.read_csv("loadDL.csv",delimiter=",")
SiDL = pd.read_csv("loadSiDL.csv",delimiter=",")
LL = pd.read_csv("loadLL.csv",delimiter=",")
DL

      Element  Node      Fx[N]   Mx[N.m]    My[N.m]      Mz[N.m]
0           1     1   1380.000  13.03690   6550.000    -5.516770
1           1     3   1380.000  13.03690   2230.000     3.351820
2           2     3   1000.000   2.79267  -9390.000     3.350420
3           2     4   1000.000   2.79267 -12500.000    -0.214014
4           3     4    741.937   4.35304 -20800.000    -0.213996
...       ...   ...        ...       ...        ...          ...
3739     4174  4797 -47700.000  -0.00028    647.157  -264.233000
3740     4175  4797 -47700.000  -0.00028    647.157  -264.233000
3741     4175  4798 -47100.000  -0.00028   8240.000 -4810.000000
3742     4176  4798 -47100.000  -0.00028   8240.000 -4810.000000
3743     4176  3919 -46500.000  -0.00028  15800.000 -9370.000000

[3744 rows x 6 columns]

In [14]:
loads = ['Fx[N]', 'My[N.m]', 'Mz[N.m]']
load_combination = DL.copy()
load_combination[loads] = 1.35 * DL[loads] + 1.35 * SiDL[loads] + 1.5  * LL[loads]
load_combination

      Element  Node         Fx[N]   Mx[N.m]      My[N.m]       Mz[N.m]
0           1     1    4880.85000  13.03690  23137.50000    -19.484660
1           1     3    4880.85000  13.03690   8095.50000     11.824782
2           2     3    3531.45000   2.79267 -32904.00000     11.819847
3           2     4    3531.45000   2.79267 -43789.50000     -0.747685
4           3     4    2618.81145   4.35304 -73110.00000     -0.747617
...       ...   ...           ...       ...          ...           ...
3739     4174  4797 -124800.00000  -0.00028    618.80865    224.578800
3740     4175  4797 -124800.00000  -0.00028    618.80865    224.578800
3741     4175  4798 -123990.00000  -0.00028  24723.00000 -13998.000000
3742     4176  4798 -123990.00000  -0.00028  24723.00000 -13998.000000
3743     4176  3919 -123180.00000  -0.00028  48823.50000 -28273.500000

[3744 rows x 6 columns]

## Column elements

In [15]:
column_lines = lines_position[lines_position["End Z"] != lines_position["Start Z"]].reset_index(drop=True)
column_lines

     Line  Node 1  Node 2  Start X  Start Y  Start Z  End X  End Y  End Z
0       1       1       5      0.0      0.0      0.0    0.0    0.0    5.0
1       2       2       6      6.0      0.0      0.0    6.0    0.0    5.0
2       3       3       7     12.0      0.0      0.0   12.0    0.0    5.0
3       4       4       8     18.0      0.0      0.0   18.0    0.0    5.0
4       9      13       9      0.0      8.0      0.0    0.0    8.0    5.0
..    ...     ...     ...      ...      ...      ...    ...    ...    ...
115   462     256     311     18.0     24.0     21.0   18.0   24.0   25.0
116   463     258     313      0.0     32.0     21.0    0.0   32.0   25.0
117   464     260     315      6.0     32.0     21.0    6.0   32.0   25.0
118   465     262     317     12.0     32.0     21.0   12.0   32.0   25.0
119   466     264     319     18.0     32.0     21.0   18.0   32.0   25.0

[120 rows x 9 columns]

In [16]:
valid_elements = column_lines["Line"].unique()

column_load_combination = load_combination[load_combination["Element"].isin(valid_elements)].copy().reset_index(drop=True)
column_load_combination

     Element  Node       Fx[N]    Mx[N.m]      My[N.m]    Mz[N.m]
0          1     1  4880.85000  13.036900   23137.5000 -19.484660
1          1     3  4880.85000  13.036900    8095.5000  11.824782
2          2     3  3531.45000   2.792670  -32904.0000  11.819847
3          2     4  3531.45000   2.792670  -43789.5000  -0.747685
4          3     4  2618.81145   4.353040  -73110.0000  -0.747617
..       ...   ...         ...        ...          ...        ...
99       450   491  3741.82305   0.008500 -172890.0000   0.163767
100      451   491  4972.35000  -1.072460 -110745.0000   0.163764
101      451   492  4972.35000  -1.072460  -96525.0000   2.948333
102      452   492  6755.04180  -0.042039    3336.1956   2.950174
103      452   482  6754.95000  -0.042039   26671.5000  -3.147581

[104 rows x 6 columns]

## Column utilisation

In [17]:
line_section.iloc[0,1]

'UC203x203x60'

In [18]:
resistances[resistances["Section"] == line_section.iloc[0,1]]

          Section       F_Rd   M_yy_Rd   M_zz_Rd
145  UC203x203x60  2712200.0  232880.0  108275.0

In [19]:
load_combination

      Element  Node         Fx[N]   Mx[N.m]      My[N.m]       Mz[N.m]
0           1     1    4880.85000  13.03690  23137.50000    -19.484660
1           1     3    4880.85000  13.03690   8095.50000     11.824782
2           2     3    3531.45000   2.79267 -32904.00000     11.819847
3           2     4    3531.45000   2.79267 -43789.50000     -0.747685
4           3     4    2618.81145   4.35304 -73110.00000     -0.747617
...       ...   ...           ...       ...          ...           ...
3739     4174  4797 -124800.00000  -0.00028    618.80865    224.578800
3740     4175  4797 -124800.00000  -0.00028    618.80865    224.578800
3741     4175  4798 -123990.00000  -0.00028  24723.00000 -13998.000000
3742     4176  4798 -123990.00000  -0.00028  24723.00000 -13998.000000
3743     4176  3919 -123180.00000  -0.00028  48823.50000 -28273.500000

[3744 rows x 6 columns]

In [20]:
line_section

     line       section
0       1  UC203x203x60
1       2  UC203x203x60
2       3  UC203x203x60
3       4  UC203x203x60
4       5  UB457x191x67
..    ...           ...
463   520  UB457x191x67
464   521  UB533x210x82
465   522  UB457x191x67
466   523  UB533x210x82
467   524  UB457x191x67

[468 rows x 2 columns]

In [21]:
# Add line column
combined_df = load_combination.copy()

combined_df = combined_df.merge(
    elements[["Element", "Line"]],
    on="Element",
    how="left"
)
combined_df

      Element  Node         Fx[N]   Mx[N.m]      My[N.m]       Mz[N.m]  Line
0           1     1    4880.85000  13.03690  23137.50000    -19.484660    53
1           1     3    4880.85000  13.03690   8095.50000     11.824782    53
2           2     3    3531.45000   2.79267 -32904.00000     11.819847    53
3           2     4    3531.45000   2.79267 -43789.50000     -0.747685    53
4           3     4    2618.81145   4.35304 -73110.00000     -0.747617    53
...       ...   ...           ...       ...          ...           ...   ...
3739     4174  4797 -124800.00000  -0.00028    618.80865    224.578800   466
3740     4175  4797 -124800.00000  -0.00028    618.80865    224.578800   466
3741     4175  4798 -123990.00000  -0.00028  24723.00000 -13998.000000   466
3742     4176  4798 -123990.00000  -0.00028  24723.00000 -13998.000000   466
3743     4176  3919 -123180.00000  -0.00028  48823.50000 -28273.500000   466

[3744 rows x 7 columns]

In [22]:
# Add section column
combined_df = combined_df.merge(
    line_section[["line", "section"]],
    left_on="Line",
    right_on="line",
    how="left"
)
combined_df = combined_df.drop(columns=["line"])
combined_df

,Element,Node,Fx[N],Mx[N.m],My[N.m],Mz[N.m],Line,section
0,1,1,4880.85000,13.03690,23137.50000,-19.484660,53,UB533x210x82
1,1,3,4880.85000,13.03690,8095.50000,11.824782,53,UB533x210x82
2,2,3,3531.45000,2.79267,-32904.00000,11.819847,53,UB533x210x82
3,2,4,3531.45000,2.79267,-43789.50000,-0.747685,53,UB533x210x82
4,3,4,2618.81145,4.35304,-73110.00000,-0.747617,53,UB533x210x82
...,...,...,...,...,...,...,...,...
3739,4174,4797,-124800.00000,-0.00028,618.80865,224.578800,466,UC203x203x60
3740,4175,4797,-124800.00000,-0.00028,618.80865,224.578800,466,UC203x203x60
3741,4175,4798,-123990.00000,-0.00028,24723.00000,-13998.000000,466,UC203x203x60
3742,4176,4798,-123990.00000,-0.00028,24723.00000,-13998.000000,466,UC203x203x60
3743,4176,3919,-123180.00000,-0.00028,48823.50000,-28273.500000,466,UC203x203x60

In [23]:
# Add resistances
combined_df = combined_df.merge(
    resistances[["Section", "F_Rd","M_yy_Rd","M_zz_Rd"]],
    left_on="section",
    right_on="Section",
    how="left"
)
combined_df = combined_df.drop(columns=["Section"])
combined_df

,Element,Node,Fx[N],Mx[N.m],My[N.m],Mz[N.m],Line,section,F_Rd,M_yy_Rd,M_zz_Rd
0,1,1,4880.85000,13.03690,23137.50000,-19.484660,53,UB533x210x82,3727500.0,731300.0,106500.0
1,1,3,4880.85000,13.03690,8095.50000,11.824782,53,UB533x210x82,3727500.0,731300.0,106500.0
2,2,3,3531.45000,2.79267,-32904.00000,11.819847,53,UB533x210x82,3727500.0,731300.0,106500.0
3,2,4,3531.45000,2.79267,-43789.50000,-0.747685,53,UB533x210x82,3727500.0,731300.0,106500.0
4,3,4,2618.81145,4.35304,-73110.00000,-0.747617,53,UB533x210x82,3727500.0,731300.0,106500.0
...,...,...,...,...,...,...,...,...,...,...,...
3739,4174,4797,-124800.00000,-0.00028,618.80865,224.578800,466,UC203x203x60,2712200.0,232880.0,108275.0
3740,4175,4797,-124800.00000,-0.00028,618.80865,224.578800,466,UC203x203x60,2712200.0,232880.0,108275.0
3741,4175,4798,-123990.00000,-0.00028,24723.00000,-13998.000000,466,UC203x203x60,2712200.0,232880.0,108275.0
3742,4176,4798,-123990.00000,-0.00028,24723.00000,-13998.000000,466,UC203x203x60,2712200.0,232880.0,108275.0
3743,4176,3919,-123180.00000,-0.00028,48823.50000,-28273.500000,466,UC203x203x60,2712200.0,232880.0,108275.0

In [24]:
# Add utilisation column
combined_df["utilisation"] = (
    (abs(combined_df["Fx[N]"]) / combined_df["F_Rd"]) +
    (abs(combined_df["My[N.m]"]) / combined_df["M_yy_Rd"]) +
    1.5 * (abs(combined_df["Mz[N.m]"]) / combined_df["M_zz_Rd"])
)
combined_df

,Element,Node,Fx[N],Mx[N.m],My[N.m],Mz[N.m],Line,section,F_Rd,M_yy_Rd,M_zz_Rd,utilisation
0,1,1,4880.85000,13.03690,23137.50000,-19.484660,53,UB533x210x82,3727500.0,731300.0,106500.0,0.033223
1,1,3,4880.85000,13.03690,8095.50000,11.824782,53,UB533x210x82,3727500.0,731300.0,106500.0,0.012546
2,2,3,3531.45000,2.79267,-32904.00000,11.819847,53,UB533x210x82,3727500.0,731300.0,106500.0,0.046108
3,2,4,3531.45000,2.79267,-43789.50000,-0.747685,53,UB533x210x82,3727500.0,731300.0,106500.0,0.060837
4,3,4,2618.81145,4.35304,-73110.00000,-0.747617,53,UB533x210x82,3727500.0,731300.0,106500.0,0.100686
...,...,...,...,...,...,...,...,...,...,...,...,...
3739,4174,4797,-124800.00000,-0.00028,618.80865,224.578800,466,UC203x203x60,2712200.0,232880.0,108275.0,0.051783
3740,4175,4797,-124800.00000,-0.00028,618.80865,224.578800,466,UC203x203x60,2712200.0,232880.0,108275.0,0.051783
3741,4175,4798,-123990.00000,-0.00028,24723.00000,-13998.000000,466,UC203x203x60,2712200.0,232880.0,108275.0,0.345801
3742,4176,4798,-123990.00000,-0.00028,24723.00000,-13998.000000,466,UC203x203x60,2712200.0,232880.0,108275.0,0.345801
3743,4176,3919,-123180.00000,-0.00028,48823.50000,-28273.500000,466,UC203x203x60,2712200.0,232880.0,108275.0,0.646758

In [25]:
# Get maximum utilisation
print(f"max utilisation = {max(combined_df["utilisation"])}")
combined_df.loc[ combined_df["utilisation"] == max(combined_df["utilisation"]) ]

max utilisation = 1.6114535319607741

,Element,Node,Fx[N],Mx[N.m],My[N.m],Mz[N.m],Line,section,F_Rd,M_yy_Rd,M_zz_Rd,utilisation
2903,3756,434,-5095800.0,0.0,-5667.91335,5891.68725,19,UC254x254x73,3305050.0,352160.0,165075.0,1.611454